"""Export i18n + recommendations for Cloudflare Pages Function."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import i18n  # noqa: E402
import recommendations  # noqa: E402

MONTH_ZH = {
    "Jan": "1月",
    "Feb": "2月",
    "Mar": "3月",
    "Apr": "4月",
    "May": "5月",
    "Jun": "6月",
    "Jul": "7月",
    "Aug": "8月",
    "Sep": "9月",
    "Oct": "10月",
    "Nov": "11月",
    "Dec": "12月",
}

bundle = {
    "TEAM_ZH": i18n.TEAM_ZH,
    "CITY_ZH": i18n.CITY_ZH,
    "VENUE_ZH": i18n.VENUE_ZH,
    "COUNTRY_ZH": i18n.COUNTRY_ZH,
    "STAGE_ZH": i18n.STAGE_ZH,
    "PHASE_ZH": i18n.PHASE_ZH,
    "TEAM_CONFEDERATION": i18n.TEAM_CONFEDERATION,
    "CONFEDERATION_ZH": i18n.CONFEDERATION_ZH,
    "STAGE_CATEGORY": i18n.STAGE_CATEGORY,
    "TIME_SLOT_ZH": i18n.TIME_SLOT_ZH,
    "NEW_FAN_PICKS": recommendations.NEW_FAN_PICKS,
    "MONTH_ZH": MONTH_ZH,
}

OUT = ROOT / "functions" / "lib" / "i18n-bundle.js"
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// Auto-generated by scripts/export_i18n_bundle.py — do not edit\n"
    f"export default {json.dumps(bundle, ensure_ascii=False, indent=2)};\n",
    encoding="utf-8",
)
print(f"Wrote {OUT}")
